# generated by datamodel-codegen:
#   filename:  agent_intent.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Kind(Enum):
    move_to = "move_to"
    use_object = "use_object"
    converse_with = "converse_with"
    idle = "idle"
    sleep = "sleep"


class AgentIntent1(BaseModel):
    """
    The action grammar (P1): the only way an agent mutates world state. Freeform strings never touch the world; anything that fails this wall is rejected.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    agent_id: constr(pattern=r"^[a-z0-9_]+$")
    tick: conint(ge=0)
    kind: Literal["move_to"]
    destination: constr(pattern=r"^[a-z0-9_]+$") = Field(..., description="location id")


class AgentIntent2(BaseModel):
    """
    The action grammar (P1): the only way an agent mutates world state. Freeform strings never touch the world; anything that fails this wall is rejected.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    agent_id: constr(pattern=r"^[a-z0-9_]+$")
    tick: conint(ge=0)
    kind: Literal["use_object"]
    object_id: constr(pattern=r"^[a-z0-9_]+$")
    interaction: constr(min_length=1) = Field(
        ..., description="verb phrase, resolved against the object's allowed states"
    )


class Mode(Enum):
    request = "request"
    accept = "accept"
    decline = "decline"


class AgentIntent3(BaseModel):
    """
    The action grammar (P1): the only way an agent mutates world state. Freeform strings never touch the world; anything that fails this wall is rejected.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    agent_id: constr(pattern=r"^[a-z0-9_]+$")
    tick: conint(ge=0)
    kind: Literal["converse_with"]
    partner_id: constr(pattern=r"^[a-z0-9_]+$")
    mode: Mode


class AgentIntent4(BaseModel):
    """
    The action grammar (P1): the only way an agent mutates world state. Freeform strings never touch the world; anything that fails this wall is rejected.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    agent_id: constr(pattern=r"^[a-z0-9_]+$")
    tick: conint(ge=0)
    kind: Literal["idle"]


class AgentIntent5(BaseModel):
    """
    The action grammar (P1): the only way an agent mutates world state. Freeform strings never touch the world; anything that fails this wall is rejected.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    agent_id: constr(pattern=r"^[a-z0-9_]+$")
    tick: conint(ge=0)
    kind: Literal["sleep"]


class AgentIntent(
    RootModel[AgentIntent1 | AgentIntent2 | AgentIntent3 | AgentIntent4 | AgentIntent5]
):
    root: AgentIntent1 | AgentIntent2 | AgentIntent3 | AgentIntent4 | AgentIntent5 = (
        Field(
            ...,
            description="The action grammar (P1): the only way an agent mutates world state. Freeform strings never touch the world; anything that fails this wall is rejected.",
            title="AgentIntent",
        )
    )
