# generated by datamodel-codegen:
#   filename:  agent_seed.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Trait(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class InitialMemory(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Hhmm(RootModel[constr(pattern=r"^([01][0-9]|2[0-3]):[0-5][0-9]$")]):
    root: constr(pattern=r"^([01][0-9]|2[0-3]):[0-5][0-9]$")


class DailyAnchors(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    wake: Hhmm
    work_start: Hhmm
    midday_meal: Hhmm
    work_end: Hhmm
    sleep: Hhmm
    evening_habit: constr(min_length=1) | None = Field(
        None, description="free text, not a time"
    )


class AgentSeed(BaseModel):
    """
    One agent seed file (content/agents/{id}.json). Relationships live only in content/relationships.json.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(pattern=r"^[a-z0-9_]+$")
    name: constr(min_length=1)
    age: conint(ge=0)
    occupation: constr(min_length=1)
    home: constr(pattern=r"^[a-z0-9_]+$") = Field(..., description="location id")
    workplace: constr(pattern=r"^[a-z0-9_]+$") = Field(..., description="location id")
    traits: list[Trait] = Field(..., min_length=1)
    bio: constr(min_length=1)
    daily_anchors: DailyAnchors
    initial_memories: list[InitialMemory] = Field(..., min_length=1)
