# generated by datamodel-codegen:
#   filename:  ledger_event.schema.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class LedgerEvent(BaseModel):
    """
    One row in the append-only run ledger — the permanent wall. Byte-equal ledger fixtures guard the sim core; metrics post-process this stream and never read sim internals live.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    run_id: UUID
    seq: conint(ge=0) = Field(..., description="monotonic per-run sequence number")
    tick: conint(ge=0)
    kind: constr(pattern=r"^[a-z0-9_]+$") = Field(
        ...,
        description="event kind, e.g. agent_moved, conversation_started, utterance, object_state_changed, treatment_injected; the set grows with the sim",
    )
    agent_id: constr(pattern=r"^[a-z0-9_]+$") | None = Field(
        ..., description="null for world-level events"
    )
    data: dict[str, Any] = Field(..., description="kind-specific payload")
