# generated by datamodel-codegen:
#   filename:  memory_record.schema.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Kind(Enum):
    observation = "observation"
    plan = "plan"
    reflection = "reflection"
    conversation_summary = "conversation_summary"


class MemoryRecord(BaseModel):
    """
    Append-only memory-stream record. Embeddings are a storage concern (memory_records.embedding in Postgres), not part of the contract. Citations are the data for belief-divergence analysis.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    run_id: UUID
    agent_id: constr(pattern=r"^[a-z0-9_]+$")
    kind: Kind
    tick: conint(ge=0)
    text: constr(min_length=1)
    importance: conint(ge=1, le=10) = Field(
        ..., description="1–10, scored at write time by the fast tier"
    )
    citations: list[UUID] | None = Field(
        None,
        description="memory_record ids this record synthesizes (reflections; persisted as citation edges)",
    )
