# generated by datamodel-codegen:
#   filename:  relationships.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class Edge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    a: constr(pattern=r"^[a-z0-9_]+$") = Field(..., description="agent id")
    b: constr(pattern=r"^[a-z0-9_]+$") = Field(..., description="agent id")
    type: constr(min_length=1)
    closeness: confloat(ge=0.0, le=1.0) = Field(
        ..., description="interaction-propensity prior"
    )
    a_view: constr(min_length=1) = Field(
        ..., description="seeds a's initial memory about b"
    )
    b_view: constr(min_length=1) = Field(
        ..., description="seeds b's initial memory about a"
    )


class Relationships(BaseModel):
    """
    Single shared edge list (content/relationships.json) — the one place relationships are edited; no symmetric duplication.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    notes: str | None = None
    edges: list[Edge] = Field(..., min_length=1)
