# generated by datamodel-codegen:
#   filename:  town_spec.schema.json

from __future__ import annotations

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class Grid(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: conint(ge=1)
    height: conint(ge=1)


class RectItem(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class DoorItem(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class Object(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(pattern=r"^[a-z0-9_]+$") = Field(
        ..., description="globally unique across the town"
    )
    name: constr(min_length=1)
    state: constr(pattern=r"^[a-z0-9_]+$")
    interactions: dict[
        constr(pattern=r"^[a-z0-9_]+$"), constr(pattern=r"^[a-z0-9_]+$")
    ] = Field(..., min_length=1)


class Location(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(pattern=r"^[a-z0-9_]+$")
    name: constr(min_length=1)
    kind: constr(min_length=1)
    rect: list[RectItem] = Field(
        ...,
        description="[x, y, width, height] in grid cells",
        max_length=4,
        min_length=4,
    )
    door: list[DoorItem] = Field(
        ...,
        description="[x, y] door cell on the rect perimeter",
        max_length=2,
        min_length=2,
    )
    privacy: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description="0 = fully public, 1 = fully private (perception / social-norms hook)",
    )
    tags: list[str]
    objects: list[Object] = Field(
        ...,
        description="Objects-with-states. interactions maps an allowed verb to the resulting state — the only way object state changes, and it is deterministic.",
    )


class AtItem(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0)


class Occluder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(pattern=r"^[a-z0-9_]+$")
    at: list[AtItem] = Field(..., max_length=2, min_length=2)
    radius: PositiveFloat
    note: str | None = None


class TownSpec(BaseModel):
    """
    Static town content (content/town.json). Generated once, frozen; the sim only reads this. Referential/geometric integrity beyond this schema is enforced by scripts/validate_content.py.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(pattern=r"^[a-z0-9_]+$")
    name: constr(min_length=1)
    grid: Grid
    description: str | None = None
    notes: str | None = None
    locations: list[Location] = Field(..., min_length=1)
    occluders: list[Occluder]
